from __future__ import annotations

MACHINE_SUMMARIES = {
    "backend": "Backend documenta una ruta web centrada en SQL Injection error-based: enumeracion de HTTP/SSH, abuso de una entrada vulnerable para extraer informacion de base de datos, obtencion de credenciales y escalada posterior mediante cracking de hashes y binarios SUID.",
    "candy": "Candy sirve como laboratorio de CMS: parte de enumeracion web, identifica Joomla, encadena credenciales/metadata con subida de archivo malicioso para obtener ejecucion y termina revisando vias locales de escalada por sudo y SUID.",
    "console-log": "Console log esta orientada a fugas de informacion en cliente y APIs: la resolucion pivota desde enumeracion web hacia datos expuestos en consola/servicio Node.js, reutiliza credenciales y cierra con abuso local de permisos SUID.",
    "extraviado": "Extraviado refuerza analisis de datos y movimiento por consola: la nota combina enumeracion basica, pistas codificadas en base64 o metadatos y uso de credenciales recuperadas para avanzar por el sistema.",
    "hiddencat": "HiddenCat es una maquina con preparacion particular del entorno y foco en servicios Java/Tomcat: combina enumeracion de puertos 8009/8080, inclusion/subida de archivos, credenciales y escalada local por SUID.",
    "internship": "Internship mezcla SQL Injection y esteganografia: la ruta parte de HTTP, valida entradas web vulnerables, recupera pistas o credenciales desde archivos y consolida acceso con tecnicas de enumeracion y post-explotacion.",
    "library": "Library conecta descubrimiento web con explotacion de Joomla y acceso SSH: tras encontrar una pista de credenciales, fuerza usuarios con Hydra y escala explotando un script Python ejecutable con privilegios mediante Python Library Hijacking.",
    "move": "Move esta centrada en LFI y movimiento entre servicios: la resolucion enumera FTP/HTTP/Grafana/API, aprovecha lectura de archivos o secretos, crackea credenciales y usa esa informacion para llegar a privilegios superiores.",
    "nodeclimb": "nodeclimb refuerza cracking de archivos protegidos y escalada Linux: la nota parte de FTP, obtiene material comprimido, rompe credenciales con John y relaciona el acceso con vias sudo/SUID y Node.js.",
    "pequenas-mentirosas": "Pequenas mentirosas es una ruta clasica de acceso por credenciales: enumera web y SSH, prueba fuerza bruta controlada y despues revisa binarios SUID para convertir el acceso inicial en privilegios elevados.",
    "psycho": "Psycho trabaja LFI y ejecucion remota con posterior abuso de Python: la resolucion identifica una inclusion de archivos, consigue ejecucion o credenciales y escala con reglas sudo y secuestro de librerias Python.",
    "reflection": "Reflection introduce una ruta web con foco en XSS y enumeracion HTTP: despues de validar superficie y credenciales, la maquina aterriza en Linux y aprovecha permisos SUID para completar la escalada.",
    "secretjenkins": "SecretJenkins relaciona Jenkins/Tomcat con enumeracion web: el writeup busca rutas y secretos expuestos, prueba credenciales y documenta como una mala exposicion de servicios permite avanzar hacia una shell.",
    "upload": "Upload es el caso directo de subida de archivos maliciosos: se identifica la funcionalidad web, se transforma en web shell o RCE y se revisan binarios locales para elevar privilegios en Linux.",
    "verdejo": "Verdejo concentra varias tecnicas en una sola ruta: enumeracion web, SSTI, cracking de contrasenas, subida o ejecucion remota y escalada por SUID, util para consultar cadenas mixtas de explotacion.",
    "vulnvault": "Vulnvault combina CMS/web exploitation con LFI y RCE: la resolucion pasa por Joomla/PHP, aprovecha lectura o ejecucion desde la aplicacion y remata con revision de permisos SUID.",
    "where-is-my-web-shell": "Where Is My Web Shell esta pensada para practicar web shells: el objetivo es localizar la funcionalidad de subida, conseguir ejecucion en el servidor y documentar la interaccion posterior con la shell.",
    "borazuwarahctf": "BorazuwarahCTF es una maquina muy facil basada en pistas y archivos: usa enumeracion inicial, analisis de metadatos o esteganografia para recuperar credenciales y acceder al servicio expuesto.",
    "breakmyssh": "BreakMySSH se enfoca en comprometer SSH: la nota revisa enumeracion de servicios, uso de fuerza bruta o cracking de credenciales y reutilizacion del acceso para completar el laboratorio.",
    "firsthacking": "FirstHacking es una introduccion a enumeracion de FTP y servicios simples: el writeup identifica puertos relevantes, reconoce versiones y aprovecha el comportamiento del servicio para obtener acceso.",
    "hedgehog": "HedgeHog plantea una trampa sencilla alrededor de web y SSH: tras enumerar HTTP, se recuperan credenciales o usuarios y se escala mediante reglas sudo mal acotadas.",
    "injection": "Injection resume una cadena de SQL Injection y login bypass: el acceso se obtiene manipulando la logica de autenticacion y despues se revisan permisos locales para escalar por SUID.",
    "obsession": "Obsession es una maquina de calentamiento para enumeracion y credenciales: combina reconocimiento de red, servicios web/FTP y pruebas controladas de credenciales hasta obtener acceso.",
    "tproot": "Tproot documenta una ruta muy facil alrededor de FTP: la resolucion confirma conectividad, enumera puertos y analiza el servicio expuesto antes de aprovechar el comportamiento vulnerable.",
    "trust": "Trust combina fuerza bruta SSH, fuzzing web y abuso de sudo: la ruta recupera credenciales desde la superficie web y escala aprovechando permisos sobre Vim.",
    "vacaciones": "Vacaciones trabaja una ruta corta de web a SSH: se enumeran puertos 22/80, se obtiene informacion util desde HTTP y se valida una escalada local por sudo o SUID.",
}

TECHNIQUE_DESCRIPTIONS = {
    "api-abuse": "Abuso de API consiste en identificar endpoints, parametros y supuestos de autorizacion para extraer datos, saltar controles o ejecutar acciones no previstas por el flujo normal.",
    "brute-force": "La fuerza bruta prueba combinaciones de usuarios, contrasenas o tokens de forma controlada. En laboratorios se usa para validar credenciales debiles; en defensa exige rate limiting, bloqueo progresivo y MFA.",
    "cms-exploitation": "La explotacion de CMS parte de fingerprinting de version, plugins, rutas administrativas y credenciales. El riesgo principal aparece cuando una cuenta permite editar plantillas, subir extensiones o modificar codigo.",
    "command-injection": "Command Injection ocurre cuando una aplicacion concatena entrada de usuario en comandos del sistema. El impacto puede ir desde lectura de archivos hasta RCE completa con el usuario del proceso vulnerable.",
    "connectivity-check": "La verificacion de conectividad confirma que el host responde y da pistas iniciales como TTL, latencia o filtrado ICMP. Es una fase de orientacion, no una prueba de explotabilidad.",
    "credential-extraction": "La extraccion de credenciales busca secretos en archivos, respuestas web, historiales, metadatos, backups o configuraciones. Cada credencial debe asociarse con su origen y alcance.",
    "hash-cracking": "El cracking de hashes convierte material cifrado o derivado en credenciales reutilizables cuando el algoritmo, formato y diccionario son adecuados. Es clave documentar formato, herramienta y evidencia.",
    "lfi": "Local File Inclusion permite leer o incluir archivos locales cuando la aplicacion usa rutas controlables por el usuario. Puede exponer secretos y, bajo ciertas condiciones, convertirse en RCE.",
    "login-bypass": "Login bypass explota fallos de logica o validacion en autenticacion. Suele aparecer cuando la aplicacion confia en parametros manipulables o concatena consultas sin controles robustos.",
    "malicious-file-upload": "La subida de archivos maliciosos abusa validaciones debiles de extension, MIME, nombre o ubicacion. Si el archivo queda ejecutable por el servidor, puede derivar en web shell o RCE.",
    "metadata-analysis": "El analisis de metadatos revisa informacion oculta en documentos, imagenes o binarios: usuarios, rutas, software, comentarios o pistas que puedan orientar la explotacion.",
    "port-enumeration": "La enumeracion de puertos identifica servicios escuchando, versiones y scripts relevantes. Es la base para decidir si buscar CVEs, probar configuraciones o pasar a enumeracion especifica por servicio.",
    "process-abuse": "El abuso de procesos observa tareas, cron jobs, scripts o servicios que se ejecutan con mas privilegios. La clave es encontrar escritura o control sobre rutas que esos procesos consumen.",
    "python-library-hijacking": "Python Library Hijacking aprovecha el orden de busqueda de modulos. Si un script privilegiado importa una libreria desde un directorio escribible, un modulo falso puede ejecutar codigo con esos privilegios.",
    "rce": "Remote Code Execution es la capacidad de ejecutar codigo en el objetivo desde una entrada remota. En una cadena de ataque suele ser el punto de paso entre explotacion web y post-explotacion.",
    "sql-injection": "SQL Injection permite alterar consultas de base de datos desde entradas no controladas. Puede exponer datos, saltar autenticacion, modificar registros o, en ciertos motores, ayudar a ejecutar codigo.",
    "ssti": "Server-Side Template Injection ocurre cuando datos de usuario se renderizan como plantilla. Dependiendo del motor, puede exponer configuracion, leer archivos o alcanzar ejecucion remota.",
    "steganography": "La esteganografia busca informacion escondida dentro de archivos aparentemente normales. En CTFs suele combinarse con strings, binwalk, steghide, metadatos y cracking de contrasenas.",
    "sudo-abuse": "El abuso de sudo revisa reglas con sudo -l, NOPASSWD, variables preservadas y binarios permitidos. Una regla demasiado amplia puede convertirse en shell privilegiada.",
    "suid-abuse": "SUID abuse explota binarios que se ejecutan con el propietario del archivo, normalmente root. Si el binario permite ejecutar comandos, leer/escribir archivos o cargar librerias, puede escalar privilegios.",
    "tty-stabilization": "La estabilizacion de TTY mejora una shell limitada para usar editores, clear, Ctrl+C y programas interactivos. No escala privilegios, pero reduce errores durante post-explotacion.",
    "web-enumeration": "La enumeracion web identifica tecnologias, rutas, parametros, directorios, paneles y comportamiento de la aplicacion. Es el puente entre puertos abiertos y una hipotesis de explotacion.",
}

SERVICE_DESCRIPTIONS = {
    "apache": "Servidor HTTP comun en laboratorios Linux; conviene revisar virtual hosts, configuracion de directorios, extensiones PHP y rutas publicas.",
    "api": "Superficie de endpoints consumidos por aplicaciones web o clientes; se analiza por rutas, metodos, autenticacion, autorizacion y validacion de parametros.",
    "ftp": "Servicio de transferencia de archivos; revisar acceso anonimo, banners, escritura, backups, versiones vulnerables y reutilizacion de credenciales.",
    "grafana": "Plataforma de observabilidad; en CTFs suele aparecer por paneles expuestos, credenciales por defecto, plugins o vulnerabilidades de lectura de archivos.",
    "http": "Servicio web generico; requiere fingerprinting, crawling, fuzzing de rutas, revision de cabeceras, codigo fuente y parametros.",
    "jenkins": "Servidor de automatizacion; un acceso administrativo o mala configuracion puede permitir ejecucion de scripts, jobs o lectura de secretos.",
    "joomla": "CMS PHP; revisar version, panel de administracion, extensiones, plantillas editables, backups y credenciales debiles.",
    "mariadb-mysql": "Motor de base de datos relacional; suele relacionarse con SQLi, credenciales reutilizadas, backups o configuraciones expuestas.",
    "nginx": "Servidor HTTP/reverse proxy; revisar alias mal configurados, rutas estaticas, proxys internos y reglas de acceso.",
    "nodejs-service": "Servicio JavaScript del lado servidor; revisar APIs, logs de consola, dependencias, child_process y exposicion de secretos.",
    "php": "Runtime frecuente en aplicaciones web; revisar uploads, includes, sesiones, errores visibles y configuracion del servidor.",
    "smb": "Servicio de comparticion Windows/Samba; enumerar shares, permisos, usuarios, null sessions y credenciales reutilizadas.",
    "ssh": "Acceso remoto cifrado; validar version, usuarios, autenticacion por clave/contrasena, fuerza bruta controlada y reutilizacion de credenciales.",
    "tomcat": "Servidor Java; revisar Manager, AJP, credenciales por defecto, despliegue de WAR y rutas administrativas.",
}

PRIVILEGE_METHOD_DESCRIPTIONS = {
    "hash-cracking-to-root": "Escalada basada en obtener hashes o material cifrado, romperlo offline y reutilizar la credencial resultante para acceder como un usuario con mas privilegios.",
    "process-abuse": "Escalada mediante procesos o tareas programadas que ejecutan archivos controlables por el atacante o consumen rutas escribibles.",
    "python-library-hijacking": "Escalada por secuestro de modulos Python cuando un script privilegiado importa librerias desde una ruta en la que el usuario puede escribir.",
    "sudo-binary-abuse": "Escalada por reglas sudo demasiado permisivas, especialmente NOPASSWD o binarios interactivos capaces de ejecutar comandos.",
    "suid-binary-abuse": "Escalada por binarios SUID que permiten leer/escribir archivos sensibles, invocar shells o ejecutar subcomandos con privilegios elevados.",
}

VULNERABILITY_GUIDANCE = {
    "exposed-error-message": {
        "description": "Mensajes de error visibles revelan rutas, consultas, versiones, usuarios o trazas internas. En explotacion ayudan a ajustar payloads; en defensa deben reducirse a mensajes controlados y logs internos.",
        "signals": ["stack traces", "errores SQL", "rutas absolutas", "versiones de framework", "mensajes distintos ante entradas manipuladas"],
        "mitigation": "Desactivar errores detallados en produccion, registrar internamente con contexto suficiente y devolver respuestas genericas al usuario.",
        "links": ["https://hacktricks.wiki/en/generic-methodologies-and-resources/pentesting-methodology.html"],
    },
    "insecure-file-upload": {
        "description": "Una subida insegura permite almacenar archivos no esperados o ejecutables. Si el servidor interpreta el archivo como codigo, la vulnerabilidad puede convertirse en web shell o RCE.",
        "signals": ["validacion solo por extension", "MIME confiado desde el cliente", "archivos publicos en ruta ejecutable", "nombres manipulables", "falta de reescritura del nombre"],
        "mitigation": "Usar allowlist estricta, validar contenido real, renombrar archivos, almacenar fuera del webroot, retirar permisos de ejecucion y servir descargas desde un controlador seguro.",
        "links": ["https://book.hacktricks.wiki/en/pentesting-web/file-upload/index.html"],
    },
    "secret-in-metadata": {
        "description": "Secretos en metadatos aparecen cuando documentos, imagenes o backups conservan usuarios, rutas, comentarios, coordenadas, software o cadenas sensibles.",
        "signals": ["EXIF con autor/ruta", "strings legibles", "comentarios en documentos", "archivos comprimidos con nombres reveladores", "pistas ocultas en imagenes"],
        "mitigation": "Limpiar metadatos antes de publicar, revisar pipelines de exportacion, bloquear secretos en repositorios y automatizar escaneo de archivos adjuntos.",
        "links": ["https://hacktricks.wiki/en/generic-methodologies-and-resources/pentesting-methodology.html"],
    },
    "sudo-misconfiguration": {
        "description": "Una mala configuracion de sudo permite ejecutar binarios o scripts con privilegios excesivos. Reglas NOPASSWD, variables preservadas o comodines pueden romper el limite entre usuario y root.",
        "signals": ["sudo -l con NOPASSWD", "binarios interactivos permitidos", "scripts root editables", "env_keep peligroso", "wildcards en sudoers"],
        "mitigation": "Limitar comandos con rutas absolutas, evitar comodines, no preservar variables peligrosas, auditar scripts permitidos y aplicar minimo privilegio.",
        "links": ["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation/index.html"],
    },
    "suid-misconfiguration": {
        "description": "Un binario SUID mal elegido ejecuta acciones como su propietario. Si ese binario permite invocar comandos, cargar archivos controlados o escribir en rutas sensibles, puede escalar a root.",
        "signals": ["permiso 4000", "binarios no estandar con SUID", "GTFOBins aplicable", "rutas escribibles usadas por el binario", "lectura/escritura privilegiada"],
        "mitigation": "Reducir SUID al minimo, retirar permisos innecesarios, usar capacidades Linux cuando aplique y monitorizar cambios de permisos privilegiados.",
        "links": ["https://book.hacktricks.wiki/en/linux-hardening/privilege-escalation/index.html"],
    },
    "unsanitized-user-input": {
        "description": "Entrada de usuario sin validacion llega a interpretes como SQL, shell o motores de plantillas. El mismo patron explica SQLi, Command Injection y SSTI: datos tratados como instrucciones.",
        "signals": ["parametros reflejados en consultas", "caracteres especiales alteran la respuesta", "errores ante comillas o separadores", "payloads que cambian logica o salida"],
        "mitigation": "Separar datos de codigo con consultas parametrizadas, APIs sin shell, plantillas seguras, validacion por allowlist y escaping contextual.",
        "links": ["https://book.hacktricks.wiki/en/pentesting-web/sql-injection/index.html", "https://book.hacktricks.wiki/pentesting-web/command-injection.html"],
    },
    "weak-credentials": {
        "description": "Credenciales debiles, por defecto o reutilizadas permiten acceso sin explotar una falla tecnica compleja. En laboratorios suele validarse con diccionarios acotados y evidencia clara del origen.",
        "signals": ["usuarios filtrados", "passwords en web/configuracion", "servicios con login remoto", "credenciales por defecto", "reutilizacion entre servicios"],
        "mitigation": "Aplicar MFA, politicas de contrasenas, bloqueo progresivo, deteccion de intentos, rotacion de secretos y eliminacion de credenciales por defecto.",
        "links": ["https://book.hacktricks.wiki/en/generic-hacking/brute-force.html"],
    },
}
